### ISSUE TITLE
Support reading servers from multiple path

### ISSUE THREAD

**Issue by n0rad** [blablacar/go-synapse#34]
Some use case require to get servers from multiple path with different server options

**Comment by n0rad** [comment]
Current service configuration look like :
```yaml
        watcher:
           ...
        serverOptions: cookie {{sha1String .Name}} check inter 2s rise 3 fall 2
        serverSort: ...
```

Since we want to support multiple sources to generate list of servers, I propose to create this arbo in the service :
```yaml
      - servers:
         - watcher:
           serverOptions:
           serverSort:
         - watcher:
           serverOptions:
           serverSort:
```

and fail if both are defined
